### ISSUE TITLE
User Story: Nonprofit User Dashboard

### ISSUE THREAD

**Issue by Code4SocialGood** [Code4SocialGood/C4SG#117]
**Requirement**
- Implement Nonprofit User Dashboard Page.
- If the current REST APIs don't satisfy your requirement, implement the API you need in backend.
- If the database table structure doesn't satisfy your requirement, modify the table in the database.
- We don't have login page yet. To simulate page activation, add a menu item called "Nonprofit User" in home page. Click this menu item to populate Nonprofit User Dashboard Page.

**Design Document**
[User Story: Nonprofit User Dashboard ](https://github.com/Code4SocialGood/C4SG/blob/master/Documentation/Design/User_Story_NonProfit_User_Dashboard.docx)

**Documentation**
Update the following document as needed during your story grooming and development:
- [Design Document](https://github.com/Code4SocialGood/C4SG/blob/master/Documentation/Design/User_Story_NonProfit_User_Dashboard.docx)
- [Rest API Document](https://github.com/Code4SocialGood/C4SG/blob/master/Documentation/Rest_API/REST_API_User.docx)
- [Table Definition Script](https://github.com/Code4SocialGood/C4SG/blob/master/Documentation/Database/Table_Definition.sql)
- [Data Load Script](https://github.com/Code4SocialGood/C4SG/blob/master/Documentation/Database/Data_Load.sql)

**Comment by Outte** [comment]
The HTML of the non-profit dashboard is nearly complete, but there are still a few things that need to be corrected. There are certain parts of the code where inappropriate form `<input>` tags are used. The inappropriate `<input>` tags have been disabled and should remain so until corrected. Here's a list of the `<input>` tags that need to be corrected If anyone else would like to correct them. 

In the "myOrganization" Form-Group:

- [ ] "category" should be a `<select>` tag. specific `<option>` tags can be determined at a later date
- [ ] "state" should be a `<select>` tag. specific `<option>` tags can be determined at a later date
- [ ] "country" should be a `<select>` tag. specific `<option>` tags can be determined at a later date

In the "createProject" Form-Group

- [ ] "remote" and "physicalAddress" should be radio type `<input>` tags
- [ ] "state" should be a `<select>` tag. specific `<option>` tags can be determined at a later date
- [ ] "country" should be a `<select>` tag. specific `<option>` tags can be determined at a later date
