### ISSUE TITLE
Project API: Map Project entity to ProjectDto in service and controller

### ISSUE THREAD

**Issue by shobhit-sri** [Code4SocialGood/C4SG#131]

**Comment by felipealves-gnu** [comment]
Is this Project entity no longer mapped?

**Comment by Code4SocialGood** [comment]
Shobbit opened this issue long time ago, unfortunately he has no time working on it. Felipe, do we still need this task, or it has already been taken care of in the current code?

**Comment by felipealves-gnu** [comment]
It's already done.
