### ISSUE TITLE
Consolidate Create Project Code [Due 2/13]

### ISSUE THREAD

**Issue by Code4SocialGood** [Code4SocialGood/C4SG#207]
In order to consolidate Create Project into one place, please:
1. Remove the submenu "Create Project" from "Projects" menu. 
2. Merge the code to: Dashboard -> Nonprofit User -> Create Project

**Comment by politologu** [comment]
we dont need to create any submenu?

**Comment by Code4SocialGood** [comment]
No we don't. We want to produce a simple, clean, professional user interface. The sub-menu you currently see on home page were created to temporarily support development. They will be removed gradually.

**Comment by Code4SocialGood** [comment]
This is what we prefer: http://www.idealist.org/
This is what we don't prefer: http://www.volunteermatch.org/
Less is more.

**Comment by politologu** [comment]
ahaa ok we will create same exactly  as this 
![capture](https://cloud.githubusercontent.com/assets/8106609/22665936/9c1dd620-ec6b-11e6-8ce6-d0e5dc873154.PNG)

**Comment by politologu** [comment]
I Like to dominate 2 colors for every web:1) white about 70 percent 2) black less than white

**Comment by Code4SocialGood** [comment]
Code for Create Project resides in: \C4SGWeb\app\project\create
