### ISSUE TITLE
Dashboard - Implement SideNav [2/17]

### ISSUE THREAD

**Issue by Code4SocialGood** [Code4SocialGood/C4SG#220]
**Task Description**

- From the application home page, click Dashboard -> Nonprofit
- The dashboard is displaying tabs.
- Your task is to replace this tab with sidenav: http://materializecss.com/side-nav.html

Reference:
- We are using Angular 2 Materialize plugin: https://github.com/InfomediaLtd/angular2-materialize

**Comment by sabrinadowla14** [comment]
Hi Jenny,

Is this for me?

Sabrina
