### ISSUE TITLE
 Project List Page - Display Projects [Due 2/24] 

### ISSUE THREAD

**Issue by Code4SocialGood** [Code4SocialGood/C4SG#281]
- **Web Path**

Home Page -> Projects

- **Requirement**

1. "x" volunteer opportunities found
The number on web page currently is a fixed number. Make it dynamic to match number of projects.

2. "x" volunteer opportunities found
Move it below project search panel, as show in the wireframe.

3. Project List
Make them 2 columns, like Volunteers page

4. Project
Add project post date as shown in wireframe.
The Rest API is: http://localhost:8080/swagger-ui.html#!/project-controller/getProjectsUsingGET
The field for post date is: createTime

5. Lower portion of the page
Remove the lower portion of the page ("My projects" text, Under Construction images, etc). That portion comes from another project list page that merged into this page. It tries to display projects in two columns.

- **Timeline**
We implement weekly sprint. This task is given a default of one week. You don't have to finish all requirements in this task, but please submit a Pull Request with whatever code change you have by 2/24. This helps us get the latest development status and plan the next sprint efficiently.

- **Source Code**

\C4SGWeb\app\project\list\

- **Reference**

Please refer to the implementation of: Home Page -> Volunteers

- **Wireframe**

![image](https://cloud.githubusercontent.com/assets/24813620/23076414/f80d0cec-f505-11e6-8c73-e235a67ff6d1.png)

**Current Page**
![project_list](https://cloud.githubusercontent.com/assets/24813620/23076864/bb588e96-f507-11e6-9f0b-06cec9aba91d.png)

**Comment by sabrinadowla14** [comment]
Hi Jenny,

Is this for me?

Thanks,

Sabrina

**Comment by sabrinadowla14** [comment]
Hi Jenny,

I am not able to see the output. Are you still trying to update your
website?

Thanks,

Sabrina

**Comment by Code4SocialGood** [comment]
Have you done:
1. Sync the fork to get the latest code from repository (instruction in development document in google drive)
2. In Eclipse IDE, run the backend as Spring Boot (instruction in setup document)
3. Run: npm install in github
4. Run: npm start
