### ISSUE TITLE
View Organization Page - Display [Due 3/1]

### ISSUE THREAD

**Issue by Code4SocialGood** [Code4SocialGood/C4SG#312]
- **Web Path**
Enter in browser: http://localhost:3000/organization/view/1

Note: This task is for Organization Detail page. Another task, #310 Nonprofit List Page - Display & View Detail, is for Organization List page. After both tasks are done, we will integrate the two page by:
Home Page -> Nonprofits -> Org Details

- **Requirement**
1. Display the page layout as designed in the wireframe below.
2. Retrieve the organization information from Rest API. and display on the page.
Rest API: GET /api/organization/search/byId/{id}
Rest API Documentation: http://localhost:8080/swagger-ui.html#!/organization-controller/getOrganizationUsingGET
3. For the "Projects" button at bottom of the page, just display the button, no need to implement the onClick() event. onClick() will be done in another task.

- **Timeline**
We implement weekly sprint. This task is given a default of one week. You don't have to finish all requirements in this task, but please submit a Pull Request with whatever code change you have by 3/1. This helps us get the latest development status and plan the next sprint efficiently.

- **Source Code**
\C4SGWeb\app\organization\view\

- *Reference**
Please refer to the implementation of: Home Page -> Volunteers -> Volunteer Details
\C4SGWeb\app\user\view\

- **Wireframe**
![image](https://cloud.githubusercontent.com/assets/24813620/23227558/f19735b6-f8fe-11e6-90c9-25af375f1943.png)

- **Current Page**
None

**Comment by sean-lloyd** [comment]
Completed work on this today and submitted PR...and a later PR to fix warnings + include icon set.
