### ISSUE TITLE
My Organization Page - Display [Due 3/2]

### ISSUE THREAD

**Issue by Code4SocialGood** [Code4SocialGood/C4SG#319]
- **Web Path**
Home Page -> John Doe -> My Organization

- **Requirement**

1. Display the page layout as designed in the wireframe below.
This page is similar as View Orgaganization Detail page, but it is in Edit mode.

2. Retrieve the organization information from Rest API. and display on the page.
Rest API: GET /api/organization/search/byId/{id}
Rest API Documentation: http://localhost:8080/swagger-ui.html
Note: We will develop a new operation, /api/organization/search/byUserId/{userId}. For now, just use the existing operation of /api/organization/search/byId/{id}. It will be an easy switch after the new operation is done.
Note: We don't have login implemented yet. Hard code an ID.

3. When Save button is clicked, save the update to database.
Rest API: PUT /api/organization/update/{id}
Note: Organization logo is not saved with this operation.

4. Organization Logo
When "Choose File" button is clicked, popup window for user to select image file from local file system.
Reference: Home Page -> John Doe -> Create Project
Note: We have another task WIP on saving the organization logo. Saving organization logo and saving organization information might be two separate operations.

- **Timeline**
We implement weekly sprint. This task is given a default of one week. You don't have to finish all requirements in this task, but please submit a Pull Request with whatever code change you have by 3/2. This helps us get the latest development status and plan the next sprint efficiently.

- **Source Code**
\C4SGWeb\app\organization\edit

- **Wireframe**
![edit organization](https://cloud.githubusercontent.com/assets/24813620/23273002/05cb85e0-f9c3-11e6-905f-6cda73ecdb6d.png)

- **Current Page**
None

**Comment by sean-lloyd** [comment]
Submitted PR.

Remaining TODO
1. Complete saving org to database when the OrganizationService has a method to do so
2. Set the editOrg variable to determine if editing or adding an org (based on route?, userid logged in?)
