### ISSUE TITLE
Login Page [Due 3/9]

### ISSUE THREAD

**Issue by Code4SocialGood** [Code4SocialGood/C4SG#320]
- **Web Path**
Home Page -> Login

- **Requirement**
1. Add: Don't have an account?
2. Add: Sign up button
3. Forgot Password: Change from button to link
Note: Just finish the above requirements. Don't add other components like facebook login, etc that is on wireframe. Those are for later release.

- **Timeline**
We follow Agile methodology and implement weekly sprint. This task is given a default of one week. You don't have to finish all requirements in this task, but please submit a Pull Request with whatever code change you have by 3/2. This helps us get the latest development status and plan the next sprint efficiently.

- **Wireframe**
![login](https://cloud.githubusercontent.com/assets/24813620/23283431/76bfc7c0-f9eb-11e6-8447-e5836bf03a8f.png)

**Comment by Hpham1000** [comment]
[Login Page CSS.txt](https://github.com/Code4SocialGood/C4SG/files/819585/Login.Page.CSS.txt)
[Login Page HTML.txt](https://github.com/Code4SocialGood/C4SG/files/819586/Login.Page.HTML.txt)

**Comment by Hpham1000** [comment]
<!doctype html>
<html>
<head>
<meta charset="utf-8">
<title>Login in Webpage</title>
	<link rel="stylesheet" type="text/css" href="css/style.css">
	<link href="Login.css" rel="stylesheet" type="text/css">
</head>
<body>
<div class="container">
  <header><h1>Navigation Bar</h1></header>
</div>

<ul>
  <li><a href="navigation1">Navigation1</a></li>
  <li><a href="navigation2">Navigation2</a></li>
  <li><a href="navigation3">Navigation3</a></li>
   <li><a href="navigation4">Navigation4</a></li>
  <li><a href="navigation5">Navigation5</a></li>
</ul>
<div class="wrap">
		<button class=".login-facebook"> Login with Facebook</button>
  <button class="login-google">Login with Google</button> 

	<p>Or	</p>
	<p>
	    <input type="text" name="emailaddress" placeholder="Email address"> 
	    <input type="password" name="password" placeholder="Password">
<form>
  <input type="checkbox" name="rememberme" value="Remember"> Remember me<br>
  </form> 
	

  </p>
  <button class="btn-login">Login</button>
  
 <p><b><a href="default.asp" target="_blank">Forgot Password</a></b></p>
  <hr>

	<p>Don't have an account? </p>
  <button class="btn-signup">Sign Up</button>

	</div>

	


<ul>
  <li><a href="navigation1">Navigation1</a></li>
  <li><a href="navigation2">Navigation2</a></li>
  <li><a href="navigation3">Navigation3</a></li>
   <li><a href="navigation4">Navigation4</a></li>
  <li><a href="navigation5">Navigation5</a></li>
</ul>
<footer>Copyright &copy; </footer>


</body>
</html>

**Comment by Hpham1000** [comment]
<!doctype html>
<html>
<head>
<style>
	body { 
	margin: 0; 
	padding: 0;
	font-family: 'Arial'; 
	background: #FFFFFF;
}

div.container {
    width: 100%;
    border: 1px solid gray;
}

header, footer {
    padding: 1em;
    color: white;
    background-color: #959595;
    clear: left;
    text-align: center;
}

.wrap {
	width: 400px; 
	overflow: hidden; 
	margin: auto; 
	margin-top: 180px; 
	padding: 20px;
	background: #CDC6C6; 
	border: 1px solid silver;
		
}

.wrap input {
	width: 400px; 
	height: 35px; 
	margin-bottom: 10px; 
	border-radius: 10px; 
	padding: 10px; 
	border: 1px solid silver;
	padding: 5px;
	
	
} 

.wrap .btn-login{
	padding: 5px;
	width: 412px;
	height: 40px; 
	background-color: #6517B1; 
	color: #fff; 
	border-radius: 3px; 
	border: 0; 
	font-size: 18px; 
	align-content: center;
	
}

.wrap .login-facebook{ 
	
}

.wrap .footer{
	background: #A8A8A8; 
	border: 1px solid silver;
}

.wrap .checkbox{
	width: 10px; 
	align-content: left;
		
}

.wrap .btn-signup {
	padding: 5px;
	width: 40px;
	height: 40px; 
	background-color: solid gray; 
	color: #D34042; 
	border-radius: 3px; 
	border: 0; 
	font-size: 15px; 
	align-content: right;
	
}

ul {
    list-style-type: none;
    margin: 0;
    padding: 0;
    overflow: hidden;
    background-color: #333;
}

li {
    float: right;
}

li a {
    display: block;
    color: white;
    text-align: center;
    padding: 55px 16px;
    text-decoration: none;
}

li a:hover {
    background-color: #A89F9F;
}
body { 
	margin: 0; 
	padding: 0;
	font-family: 'Arial'; 
	background: #FFFFFF;
}

div.container {
    width: 100%;
    border: 1px solid gray;
}

header, footer {
    padding: 1em;
    color: white;
    background-color: #959595;
    clear: left;
    text-align: center;
}

.wrap {
	width: 400px; 
	overflow: hidden; 
	margin: auto; 
	margin-top: 180px; 
	padding: 20px;
	background: #CDC6C6; 
	border: 1px solid silver;
		
}

.wrap input {
	width: 400px; 
	height: 35px; 
	margin-bottom: 10px; 
	border-radius: 10px; 
	padding: 10px; 
	border: 1px solid silver;
	padding: 5px;
	
	
} 

.wrap .btn-login{
	padding: 5px;
	width: 412px;
	height: 40px; 
	background-color: #6517B1; 
	color: #fff; 
	border-radius: 3px; 
	border: 0; 
	font-size: 18px; 
	align-content: center;
	
}

.wrap .login-facebook{ 
	
}

.wrap .footer{
	background: #A8A8A8; 
	border: 1px solid silver;
}

.wrap .checkbox{
	width: 10px; 
	align-content: left;
		
}

.wrap .btn-signup {
	padding: 5px;
	width: 40px;
	height: 40px; 
	background-color: solid gray; 
	color: #D34042; 
	border-radius: 3px; 
	border: 0; 
	font-size: 15px; 
	align-content: right;
	
}

ul {
    list-style-type: none;
    margin: 0;
    padding: 0;
    overflow: hidden;
    background-color: #333;
}

li {
    float: right;
}

li a {
    display: block;
    color: white;
    text-align: center;
    padding: 55px 16px;
    text-decoration: none;
}

li a:hover {
    background-color: #A89F9F;
}
body { 
	margin: 0; 
	padding: 0;
	font-family: 'Arial'; 
	background: #FFFFFF;
}

div.container {
    width: 100%;
    border: 1px solid gray;
}

header, footer {
    padding: 1em;
    color: white;
    background-color: #959595;
    clear: left;
    text-align: center;
}

.wrap {
	width: 400px; 
	overflow: hidden; 
	margin: auto; 
	margin-top: 180px; 
	padding: 20px;
	background: #CDC6C6; 
	border: 1px solid silver;
		
}

.wrap input {
	width: 400px; 
	height: 35px; 
	margin-bottom: 10px; 
	border-radius: 10px; 
	padding: 10px; 
	border: 1px solid silver;
	padding: 5px;
	
	
} 

.wrap .btn-login{
	padding: 5px;
	width: 412px;
	height: 40px; 
	background-color: #6517B1; 
	color: #fff; 
	border-radius: 3px; 
	border: 0; 
	font-size: 18px; 
	align-content: center;
	
}

.wrap .login-facebook{ 
	
}

.wrap .footer{
	background: #A8A8A8; 
	border: 1px solid silver;
}

.wrap .checkbox{
	width: 10px; 
	align-content: left;

		
}

.wrap .btn-signup {
	padding: 5px;
	width: 40px;
	height: 40px; 
	background-color: solid gray; 
	color: #D34042; 
	border-radius: 3px; 
	border: 0; 
	font-size: 15px; 
	align-content: right;
	
}

ul {
    list-style-type: none;
    margin: 0;
    padding: 0;
    overflow: hidden;
    background-color: #333;
}

li {
    float: right;
}

li a {
    display: block;
    color: white;
    text-align: center;
    padding: 55px 16px;
    text-decoration: none;
}

li a:hover {
    background-color: #A89F9F;
}
</style>
<meta charset="utf-8">
<title>Login in Webpage</title>
	<link rel="stylesheet" type="text/css" href="css/style.css">
	<link href="Login.css" rel="stylesheet" type="text/css">
</head>
<body>
<div class="container">
  <header><h1>Navigation Bar</h1></header>
</div>

<ul>
  <li><a href="navigation1">Navigation1</a></li>
  <li><a href="navigation2">Navigation2</a></li>
  <li><a href="navigation3">Navigation3</a></li>
   <li><a href="navigation4">Navigation4</a></li>
  <li><a href="navigation5">Navigation5</a></li>
</ul>
<div class="wrap">
		<button class=".login-facebook"> Login with Facebook</button>
  <button class="login-google">Login with Google</button> 

	<p>Or	</p>
	<p>
	    <input type="text" name="emailaddress" placeholder="Email address"> 
	    <input type="password" name="password" placeholder="Password">
<form>
  <input type="checkbox" name="rememberme" value="Remember"> Remember me<br>
  </form> 
	

  </p>
  <button class="btn-login">Login</button>
  
 <p><b><a href="default.asp" target="_blank">Forgot Password</a></b></p>
  <hr>

	<p>Don't have an account? </p>
  <button class="btn-signup">Sign Up</button>

	</div>


<ul>
  <li><a href="navigation1">Navigation1</a></li>
  <li><a href="navigation2">Navigation2</a></li>
  <li><a href="navigation3">Navigation3</a></li>
   <li><a href="navigation4">Navigation4</a></li>
  <li><a href="navigation5">Navigation5</a></li>
</ul>
<footer>Copyright &copy; </footer>


</body>
</html>
