### ISSUE TITLE
Rest API - Project Controller- Search by Organization [Due 3/13]

### ISSUE THREAD

**Issue by Code4SocialGood** [Code4SocialGood/C4SG#329]
- **Requirement**
Create a new operation to search projects by organization ID.
Operation: GET /api/project/search/byOrganizationId/{organizationId}

- **Rest API Document**
http://localhost:8080/swagger-ui.html

- **Timeline**
We implement weekly sprint. This task is given a default of one week. You don't have to finish all requirements in this task, but please submit a Pull Request with whatever code change you have by 3/13. This helps us get the latest development status and plan the next sprint efficiently.

**Comment by arpitsrm** [comment]
For the below request :
http://localhost:8080/api/projects/search/byOrganization/1

I am able to get the below response :
[
{
"id": 1,
"name": "WebSite Construction",
"image": "assets/project/Project_TeensGive.png",
"description": "Development of a new website based on one of the available CMS website templates (such as Wordpress, Squarespace, or Drupal. Training to ensure Organization's staff members can update content and manage the site post-launch. Note: Only includes websites built on CMS based platforms. This is not a website from scratch.",
"status": "A",
"email": null,
"organization": {
"id": 1,
"name": "Teens Give",
"url": "http://www.teensgive.org",
"logo": "Logo_teensGive",
"description": "Teens Give Organization",
"address1": "7451 North William Court",
"address2": null,
"state": "NY",
"country": "USA",
"status": "ACTIVE"
}
}
]

Can I commit the code or I should get it verified and write Test cases? Can some one assist me on the code check in guidelines here?

**Comment by Code4SocialGood** [comment]
Done with PR
