### ISSUE TITLE
Integration with Slack Chat

### ISSUE THREAD

**Issue by Code4SocialGood** [Code4SocialGood/C4SG#388]
- **Background**
C4SG web application will interface with Slack to provide chat room functionality.

- **Requirement**
1. Read the requirement and technical approach document attached.
2. Research on Slack's Java API
3. Define Rest API endpoints, and the supporting Slack API calls. 
4. Create development tasks, one for each API endpoint. 

- **Document**
[Vision - Online Chat.docx](https://github.com/Code4SocialGood/C4SG/files/812436/Vision.-.Online.Chat.docx)
[Use Case Specification - Online Chat.docx](https://github.com/Code4SocialGood/C4SG/files/812437/Use.Case.Specification.-.Online.Chat.docx)
[Chat Technical Design and Slack Integration.docx](https://github.com/Code4SocialGood/C4SG/files/812438/Chat.Technical.Design.and.Slack.Integration.docx)

**Comment by politologu** [comment]
GREAT :)

**Comment by Code4SocialGood** [comment]
This issue was moved to Code4SocialGood/c4sg-services#3
