### ISSUE TITLE
Setup hosting environment for the web application

### ISSUE THREAD

**Issue by Code4SocialGood** [Code4SocialGood/C4SG#4]
**Options under consideration**

Option 1. PaaS (Prefered)
Heroku, OpenShift, AWS, Docket, Google App Engine, CoudFoundry, Cloudbees

Option 2: VPS
BlueHost, Digital Ocean, Hostgator, etc

**Comment by wjhurley** [comment]
I had to set up two different repos to deploy to Heroku. The front end repo is https://github.com/wjhurley/c4sg-web.git and is deployed to https://c4sg-web.herokuapp.com. The back end repo is https://github.com/wjhurley/c4sg-svc.git and is deployed to https://c4sg.herokuapp.com.

**Comment by Code4SocialGood** [comment]
Done.
