### ISSUE TITLE
Best Practice - How to store properties for an open source project

### ISSUE THREAD

**Issue by Code4SocialGood** [Code4SocialGood/C4SG#407]
1. Research: what is the best practice to store properties in property file, for an open source project in Github?
2. What should we do in our application?

**Comment by russon77** [comment]
@Code4SocialGood since we're hosting with Heroku, we should probably use environment variables.

**Comment by russon77** [comment]
https://www.npmjs.com/package/env-cmd makes it easy to use different environment files (or just the one) for managing credentials/secrets

**Comment by Code4SocialGood** [comment]
So those environment variables are still maintained in files? Not entries in server?

**Comment by russon77** [comment]
@Code4SocialGood what i did in another project was create a "template" .env file, like

```
C4SG_DB_URL=blank
C4SG_DB_USER=blank
```

and the developer is required to "fill in the blanks". in Heroku, the environment variables are configured in the app dashboard.

**Comment by Code4SocialGood** [comment]
Solution identified.
