### ISSUE TITLE
Best Practice - Use Gradle to Build Web Application

### ISSUE THREAD

**Issue by Code4SocialGood** [Code4SocialGood/C4SG#418]
Our backend and frontend reside on two directories in one github repository. 
We have gradle build in place for backend application. 

Research how to use gradle to build war file for frontend.
Research how gradle handles both backend and frontend build seamlessly in a web application.

Share the research result with the team to decide the next step.

**Comment by russon77** [comment]
there's a `static` directory from which Spring serve files. basically the pattern is

- use the gradle plugins for npm, node
- make sure dependencies are installed with `npm install`
- build frontend: `npm build --aot --prod # optionally specify environment`
- copy files from `dist/` to Spring's `static` folder

**Comment by Code4SocialGood** [comment]
No gradle for frontend build.
