### ISSUE TITLE
Rest API - User - Error on getUsers

### ISSUE THREAD

**Issue by Code4SocialGood** [Code4SocialGood/C4SG#427]
Endpoint: GET /api/users

Error: 
{
  "timestamp": 1488709428798,
  "status": 500,
  "error": "Internal Server Error",
  "exception": "org.springframework.orm.jpa.JpaSystemException",
  "message": "could not deserialize; nested exception is org.hibernate.type.SerializationException: could not deserialize",
  "path": "/api/users"
}

**Comment by felipealves-gnu** [comment]
@jekcosty Can you help me on that ?

**Comment by arpitsrm** [comment]
@felipealves-gnu  I had a look at the bug.. Hibernate throws error when it tries to deserialize "location" of DataType=Point.  
I am trying to find out the work around for the same

**Comment by rclong1221** [comment]
I found the problem and am requesting a PR at https://github.com/Code4SocialGood/C4SG/pull/481
