### ISSUE TITLE
Enable Public CORS Policy on all Controllers

### ISSUE THREAD

**Issue by russon77** [Code4SocialGood/C4SG#430]
i.e. for projects

    Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://c4sg.herokuapp.com/api/projects/all. (Reason: CORS header ‘Access-Control-Allow-Origin’ missing).

**Comment by arpitsrm** [comment]
Hi,
I do not get this issue in my local. Getting the expected response and the code has the @CrossOrigin annotated on every endPoint already.

**Comment by Code4SocialGood** [comment]
@arpitsrm, You are correct. CrossOrigin should have been taken care of at backend, so that localhost:4200 could communicate successfully with localhost:8080. I assume @russon77 is looking into frontend on how to address the error, he might provide some hints if changes are expected at backend.

**Comment by Code4SocialGood** [comment]
This issue was moved to Code4SocialGood/c4sg-services#7
