### ISSUE TITLE
Rest API - Project - Search by Organization

### ISSUE THREAD

**Issue by Code4SocialGood** [Code4SocialGood/C4SG#450]
Add an operation in Project Controller:
- Description: Returns a list of projects posted by an organization
- Signature: /api/projects/search/byOrganization/{id}

**Comment by arpitsrm** [comment]
For the below request :
http://localhost:8080/api/projects/search/byOrganization/1

I am able to get the below response :
[
  {
    "id": 1,
    "name": "WebSite Construction",
    "image": "assets/project/Project_TeensGive.png",
    "description": "Development of a new website based on one of the available CMS website templates (such as Wordpress, Squarespace, or Drupal. Training to ensure Organization's staff members can update content and manage the site post-launch. Note: Only includes websites built on CMS based platforms. This is not a website from scratch.",
    "status": "A",
    "email": null,
    "organization": {
      "id": 1,
      "name": "Teens Give",
      "url": "http://www.teensgive.org",
      "logo": "Logo_teensGive",
      "description": "Teens Give Organization",
      "address1": "7451 North William Court",
      "address2": null,
      "state": "NY",
      "country": "USA",
      "status": "ACTIVE"
    }
  }
]

Can I commit the code or I should get it verified and write Test cases? Can some one assist me on the code check in guidelines here?

**Comment by Code4SocialGood** [comment]
Close this issue. It is duplicate of #329
