### ISSUE TITLE
Rest API - Project - Search By User

### ISSUE THREAD

**Issue by Code4SocialGood** [Code4SocialGood/C4SG#467]
Develop a new endpoint:
1. Retrieve a list of projects that user has connections with. The connection can be either bookmarked or applied.
2. In the return list, bookmarked projects listed first, applied projects listed second 
3. The bookmarked projects and the applied projects are sorted by timestamp in descending order. The timestamp is the time that user/project relationship is created.

**Comment by arpitsrm** [comment]
Hi @Code4SocialGood , @felipealves-gnu 
 I have few questions regarding the tasks : 
1. There is a status column in project table and status column in user_projects table as well. Which one should be considered and displayed in the response.
2. There is a ProjectDTO already in code base but it has only few variables. Can I reuse that or create a new DTO with full Project object Data?
3. Currently, user_project table does not have created_date column. Should I create one to fulfil the requirement.

**Comment by Code4SocialGood** [comment]
1. Status
I am not sure what option values suppose to be for the status in user_project table. So far, projects that user applied to, and project user bookmarked, will go to that table. So let's use 'B' for bookmark and 'A' for applied. BTW, we had a task on documenting database by ERD and data dictionary. (https://github.com/Code4SocialGood/C4SG/issues/109)

2. Reuse ProjectDTO.

3. Timestamp
We won't have auditing columns like create timestamp or update timestamp in the table. It will be take care of by Envers. (https://github.com/Code4SocialGood/C4SG/issues/129). Let's ignore that create_date field in our code at this time.

**Comment by arpitsrm** [comment]
So I am not clear with the 3rd Point i.e. TimeStamp one
The requirement says
The bookmarked projects and the applied projects are sorted by timestamp in descending order. The timestamp is the time that user/project relationship is created.

How are we supposed to sort if we do not have the timeStamp in the user/project relationship??

Or can we skip that requirement till we get Envers in place?

**Comment by Code4SocialGood** [comment]
You are correct, we don't know how to sort until Envers is in place. Let's skip that requirement.

**Comment by arpitsrm** [comment]
@Code4SocialGood @felipealves-gnu : Submitted PR #484
