### ISSUE TITLE
My Projects Page - Add Button

### ISSUE THREAD

**Issue by Code4SocialGood** [Code4SocialGood/C4SG#469]
- **Web Path**
Home Page -> John Doe -> My Projects

- **Requirement**
1. Add a button on top of the page: Create New Project
2. When the button is clicked, redirect to Create Project page

**Comment by Hpham1000** [comment]
Hi Jenny - 
Can I give this ticket a go? 

HP

**Comment by Code4SocialGood** [comment]
Of course, place your name as assignee on this task, then you are ready to go!

**Comment by Hpham1000** [comment]
Thank you Jenny!!
