### ISSUE TITLE
Create Project Page - Remove Cancel Button

### ISSUE THREAD

**Issue by Code4SocialGood** [Code4SocialGood/C4SG#479]
- **Web Path**
Home Page -> John Doe -> Create Project

- **Requirement**
Remove Cancel Button

**Comment by mddubey** [comment]
Hello guys, I am just starting with this simple thing. Is there a doc for how to contribute ?

**Comment by Code4SocialGood** [comment]
This issue was moved to Code4SocialGood/c4sg-web#8
